### ISSUE TITLE
photos

### ISSUE THREAD

**Issue by soniapello** [dirkk0/Shadertoy2Threejs#1]
there's this guy photo everywhere in your [article](https://hackernoon.com/converting-shaders-from-shadertoy-to-threejs-fe17480ed5c6)
 https://avatars2.githubusercontent.com/u/8640392?s=400&v=4

**Comment by dirkk0** [comment]
thanks for the hint!

The original article seems to be ok:
 https://medium.com/hackernoon/converting-shaders-from-shadertoy-to-threejs-fe17480ed5c6

So I guess the conversion to the other website (that was not done by us) failed at some point.
Not sure if there is anything that I can do about it?
